In [ ]:
1. Display Fibonacci series up to 10 terms
2. Use a loop to display elements from a given list present at odd index positions
3. Create a recursive function
4. Create a list by picking an odd-index item from the first list and even index items from the second
5. Checks if one set is a subset or superset of another set. If found, delete all elements from that set
6. Change value of a key in a nested dictionary
7. Create a 4X2 integer array and Prints its attributes
8. Following is the provided numPy array. Return array of items by taking the third column from all rows
9. Create a result array by adding the following two NumPy arrays.
    Next, modify the result array by calculating the square of each element
10.Create a Python set such that it shows the element from both lists in a pair
11. How to get the items of series A not present in series B?
12. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
13. How to find the positions of numbers that are multiples of 3 from a series?


# 1. Display Fibonacci series up to 10 terms

In [59]:
def fibo(n):
    
    if n==1:
        return 1
    elif n==0:
        return 1
    return n+fibo(n-1)
    
    

In [60]:
fibo(10)

55

In [63]:
# assuming 1st ans 2nd element to be 1 ,1
fib_lst=[1,1]
n=10

for i in range(n-2):
    x=fib_lst[i]+fib_lst[i+1]
    fib_lst.append(x)
print(fib_lst)  
print("10th element of fibbonacci series is ",fib_lst[9])

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
10th element of fibbonacci series is  55


# 2. Use a loop to display elements from a given list present at odd index positions

In [123]:
lst=[10,15,89,23,45,78,15,26,48,23]
res=[]
for i in range(len(lst)):
    if i%2!=0:
        res.append(lst[i])
print(res)

[15, 23, 78, 26, 23]


# 3. Create a recursive function

In [3]:
# factorial
def facto(n):
    if n==0:
        return 1
    elif n==1:
        return 1
    return n*facto(n-1)

In [4]:
facto(5)

120

# 4. Create a list by picking an odd-index item from the first list and even index items from the second

In [65]:
lst1=[12,45,12,23,45,59,26,15,48,78]  # odd index items only
lst2=[56,23,48,96,35,12,33,44,75,99]    # even index items only
lst3=[]

for i in range(len(lst1)):
    if i%2 ==0:
        lst3.append(lst2[i])
    elif i%2!=0:
        lst3.append(lst1[i])
print(lst3)

[56, 45, 48, 23, 35, 59, 33, 15, 75, 78]


# 5. Checks if one set is a subset or superset of another set. If found, delete all elements from that set

In [122]:
# Cheking set_a is subset of uviversal set univ and removing the elements from set_a

univ={i for i in range(50)}
set_a={5,10,15,20,25,30,35,40}
if univ & set_a == set_a:
    print("all the elements are in Univ set")
    set_a=set_a -univ&set_a
    print(set_a)
else:
    x=set_a -univ&set_a
    print("This element is not in Unive set ",x)
    print(x)
    print(set_a=x)
    
    


all the elements are in Univ set
set()


# 6. Change value of a key in a nested dictionary

In [12]:
dict1={"name":"Ashish","cars":["BMW","ShellX","Bently","Porshe"]}
dict1["name"]="Ajay"
dict1['cars'][1]="Mercedes"

In [13]:
dict1

{'name': 'Ajay', 'cars': ['BMW', 'Mercedes', 'Bently', 'Porshe']}

# 7. Create a 4X2 integer array and Prints its attributes

In [124]:
import numpy as np
arr=np.random.randint(1,11,8).reshape(4,2)
print(arr)

[[ 5  2]
 [10  5]
 [ 4 10]
 [ 4  4]]


# `8`. Following is the provided numPy array. Return array of items by taking the third column from all rows

In [125]:

arr2=np.random.randint(1,11,9).reshape(3,3)
print(arr2)

[[ 4  5  8]
 [ 9  4  2]
 [ 5 10  2]]


In [126]:
arr3=arr2[:,2:]
print(arr3)

[[8]
 [2]
 [2]]


In [127]:
print(arr3.reshape(1,3))

[[8 2 2]]


# 9. Create a result array by adding the following two NumPy arrays.Next, modify the result array by calculating the square of each element

In [29]:
arr1=np.random.randint(1,6,9).reshape(3,3)
arr2=np.random.randint(6,11,9).reshape(3,3)

In [30]:
arr1

array([[2, 4, 5],
       [2, 1, 1],
       [1, 4, 1]])

In [31]:
arr2

array([[ 9,  9,  6],
       [ 8, 10,  8],
       [ 6, 10,  6]])

In [33]:
arr3=arr1+arr2
arr3

array([[11, 13, 11],
       [10, 11,  9],
       [ 7, 14,  7]])

In [35]:
result=arr3**2
result

array([[121, 169, 121],
       [100, 121,  81],
       [ 49, 196,  49]])

# 10.Create a Python set such that it shows the element from both lists in a pair

In [49]:
A=[12,45,78,56,59]
B=[12,56,48,33,97]
C=set()

for i in range(len(A)):
    x=(A[i],B[i])
    C.add(x)
    
print(C)

{(56, 33), (78, 48), (12, 12), (45, 56), (59, 97)}


# 11. How to get the items of series A not present in series B?


In [130]:
# requirement A`=>  A-(A & B)

A={12,45,78,56,59,99,101}
B={12,56,48,33,97}
c=A&B
res=A-c
print(res)


{99, 101, 45, 78, 59}


# 12. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?



In [145]:
import pandas as pd

# generating Random numbers
np.random.seed(555)
arr=np.random.randint(1,11,15)

# converting it to a dataframe
df=pd.DataFrame(arr)
df.astype("str")

# sorting the top  2 repeated elements
df.value_counts().head(2)

# replacing the other elements with word other
for i in df.values:
    if i!=7 and i!=1:
        df.replace(i,"other",inplace=True)
df

0
0   other
1   other
2   other
3       7
4       7
5   other
6       1
7   other
8       1
9   other
10      7
11      7
12  other
13  other
14      1

# 13. How to find the positions of numbers that are multiples of 3 from a series?

In [146]:
lst=[45,89,63,36,88,72,10,32]
res=[]
for i in range(len(lst)):
    if lst[i]%3==0:
        res.append(i)
res

[0, 2, 3, 5]